### ISSUE TITLE
Static classes within a class

### ISSUE THREAD

**Issue by KennyGoers** [zserge/log#3]
I'm having an issue with the log() method at the tag() call crashing inside a child static class, in general I like what you've done here!

**Comment by zserge** [comment]
Can you please give some more details? Like what is the exception that crashes things?
I think I've coverted the logging of the static inner classes (see `src/test/java/trikita/log/LogFormatTest.java`, there are many static classes like `LogWithTag`, `LogWithoutTag` etc) and they seemed to work just fine.

**Comment by KennyGoers** [comment]
Maybe I was wrong about the static part, in the class it was crashing it
also has a local class variable "tag". I'll dig a bit more.

**Comment by KennyGoers** [comment]
That was it, if a static class has a member "tag" (I was logging instances of a class with the tag) once I removed the local variable it worked fine. If you can't find the bit of code that caused the problem, I will change back and get you a proper stack trace...

**Comment by zserge** [comment]
Yeah.. A stack trace (of a simple code snippet to reproduce) would be helpful.
I tried adding local method variables called "tag" (String type), added/removed static class members called "tag", and tests still pass and it doesn't crash.

**Comment by KennyGoers** [comment]
I'll see what I can do, I just removed the tag member variable and it
worked after that...

**Comment by zserge** [comment]
Ok, one might get a NullPointerException if the `tag` class member is not static, e.g. if you have `private final String tag = "MyClass"` instead of `private static final String tag = "MyClass"`. Can you please tell if this is your case?

I think I can catch the NPE in my `Log.tag()` method as well and ignore it. Which means that a non-static field "tag" won't work as the log tag actually, unless I figure out how to get the caller's "this" object, and hope that the caller's method is not static.

**Comment by zserge** [comment]
Added a catch for NPE in 1.1.5. Now classes may have a non-static tag attribute and no crash will happen (but it won't be used as log tag though). If you still have problems - please reopen this issue.
